In [ ]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
data_route = '/content/gdrive/MyDrive/분석용데이터.csv'

In [ ]:
accident = pd.read_csv(data_route, encoding='euc-kr')
accident

,사고원인코드명_사고종별,기온(°C),강수량(mm),풍속(m/s),습도(%),이슬점온도(°C),현지기압(hPa),적설(cm),지면온도(°C)
0,실족추락,2.0,NaN,1.5,71.0,-2.7,1005.9,NaN,0.7
1,실족추락,2.0,NaN,1.5,71.0,-2.7,1005.9,NaN,0.7
2,기타산악,11.2,NaN,1.5,37.0,-2.9,1009.8,NaN,9.9
3,실족추락,3.1,NaN,0.2,78.0,-0.3,1018.4,NaN,0.1
4,일반조난,5.4,NaN,0.6,62.0,-1.3,1009.3,NaN,0.9
...,...,...,...,...,...,...,...,...,...
14481,일반조난,6.4,NaN,1.8,72.0,1.7,1012.4,NaN,7.0
14482,기타산악,13.5,NaN,2.2,70.0,8.1,1010.8,NaN,12.5
14483,기타산악,13.5,NaN,2.2,70.0,8.1,1010.8,NaN,12.5
14484,기타산악,12.2,NaN,1.3,70.0,6.8,1011.4,NaN,11.3
14485,일반조난,-4.9,NaN,2.7,27.0,-21.0,1023.7,NaN,-0.1

In [ ]:
target = pd.DataFrame(accident['사고원인코드명_사고종별'])

In [ ]:
target

      사고원인코드명_사고종별
0             실족추락
1             실족추락
2             기타산악
3             실족추락
4             일반조난
...            ...
14481         일반조난
14482         기타산악
14483         기타산악
14484         기타산악
14485         일반조난

[14486 rows x 1 columns]

In [ ]:
accident = accident.fillna(0)
accident

,사고원인코드명_사고종별,기온(°C),강수량(mm),풍속(m/s),습도(%),이슬점온도(°C),현지기압(hPa),적설(cm),지면온도(°C)
0,실족추락,2.0,0.0,1.5,71.0,-2.7,1005.9,0.0,0.7
1,실족추락,2.0,0.0,1.5,71.0,-2.7,1005.9,0.0,0.7
2,기타산악,11.2,0.0,1.5,37.0,-2.9,1009.8,0.0,9.9
3,실족추락,3.1,0.0,0.2,78.0,-0.3,1018.4,0.0,0.1
4,일반조난,5.4,0.0,0.6,62.0,-1.3,1009.3,0.0,0.9
...,...,...,...,...,...,...,...,...,...
14481,일반조난,6.4,0.0,1.8,72.0,1.7,1012.4,0.0,7.0
14482,기타산악,13.5,0.0,2.2,70.0,8.1,1010.8,0.0,12.5
14483,기타산악,13.5,0.0,2.2,70.0,8.1,1010.8,0.0,12.5
14484,기타산악,12.2,0.0,1.3,70.0,6.8,1011.4,0.0,11.3
14485,일반조난,-4.9,0.0,2.7,27.0,-21.0,1023.7,0.0,-0.1

In [ ]:
num_of_falls = len(accident[accident['사고원인코드명_사고종별'] == '야생식물 섭취 중독'])

# 결과를 출력합니다.
print(num_of_falls)

15

In [ ]:
df = accident[['기온(°C)', '강수량(mm)','풍속(m/s)','습도(%)', '이슬점온도(°C)', '적설(cm)','지면온도(°C)']]
df.loc[df['강수량(mm)']==0.0, '강수여부'] = 0
df.loc[df['강수량(mm)']>0.0, '강수여부'] = 1
df.loc[df['적설(cm)']==0.0, '적설여부'] = 0
df.loc[df['적설(cm)']>0.0, '적설여부'] = 1

df

<ipython-input-105-9a8b637d8f82>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['강수량(mm)']==0.0, '강수여부'] = 0

,기온(°C),강수량(mm),풍속(m/s),습도(%),이슬점온도(°C),적설(cm),지면온도(°C),강수여부,적설여부
0,2.0,0.0,1.5,71.0,-2.7,0.0,0.7,0.0,0.0
1,2.0,0.0,1.5,71.0,-2.7,0.0,0.7,0.0,0.0
2,11.2,0.0,1.5,37.0,-2.9,0.0,9.9,0.0,0.0
3,3.1,0.0,0.2,78.0,-0.3,0.0,0.1,0.0,0.0
4,5.4,0.0,0.6,62.0,-1.3,0.0,0.9,0.0,0.0
...,...,...,...,...,...,...,...,...,...
14481,6.4,0.0,1.8,72.0,1.7,0.0,7.0,0.0,0.0
14482,13.5,0.0,2.2,70.0,8.1,0.0,12.5,0.0,0.0
14483,13.5,0.0,2.2,70.0,8.1,0.0,12.5,0.0,0.0
14484,12.2,0.0,1.3,70.0,6.8,0.0,11.3,0.0,0.0
14485,-4.9,0.0,2.7,27.0,-21.0,0.0,-0.1,0.0,0.0

In [ ]:
import scipy.stats as stats

for item in df:
  for item2 in df:
    if stats.pearsonr(df[item],df[item2]).statistic > 0.5:
      print(item,"+",item2,"=",stats.pearsonr(df[item],df[item2]))

기온(°C) + 기온(°C) = PearsonRResult(statistic=1.0, pvalue=0.0)
기온(°C) + 이슬점온도(°C) = PearsonRResult(statistic=0.8585429200579182, pvalue=0.0)
기온(°C) + 지면온도(°C) = PearsonRResult(statistic=0.8912461287788654, pvalue=0.0)
강수량(mm) + 강수량(mm) = PearsonRResult(statistic=0.9999999999999937, pvalue=0.0)
풍속(m/s) + 풍속(m/s) = PearsonRResult(statistic=1.0, pvalue=0.0)
습도(%) + 습도(%) = PearsonRResult(statistic=1.0, pvalue=0.0)
습도(%) + 이슬점온도(°C) = PearsonRResult(statistic=0.6585504159646621, pvalue=0.0)
이슬점온도(°C) + 기온(°C) = PearsonRResult(statistic=0.8585429200579182, pvalue=0.0)
이슬점온도(°C) + 습도(%) = PearsonRResult(statistic=0.6585504159646621, pvalue=0.0)
이슬점온도(°C) + 이슬점온도(°C) = PearsonRResult(statistic=1.0, pvalue=0.0)
이슬점온도(°C) + 지면온도(°C) = PearsonRResult(statistic=0.6923404855520681, pvalue=0.0)
적설(cm) + 적설(cm) = PearsonRResult(statistic=0.999999999999998, pvalue=0.0)
적설(cm) + 적설여부 = PearsonRResult(statistic=0.6480888066398924, pvalue=0.0)
지면온도(°C) + 기온(°C) = PearsonRResult(statistic=0.8912461287788654, pvalue=0.0)
지면온도(°C) + 이슬점온도(°C) = PearsonRResult(statistic=0.6923404855520681, pvalue=0.0)
지면온도(°C) + 지면온도(°C) = PearsonRResult(statistic=1.0, pvalue=0.0)
강수여부 + 강수여부 = PearsonRResult(statistic=0.9999999999999989, pvalue=0.0)
적설여부 + 적설(cm) = PearsonRResult(statistic=0.6480888066398924, pvalue=0.0)
적설여부 + 적설여부 = PearsonRResult(statistic=0.9999999999999936, pvalue=0.0)

In [ ]:
target.replace({'개인(급.만성)질환':1}, inplace= True)
target.replace({'개인질환':1}, inplace= True)
target.replace({'고온환경질환':1}, inplace= True)
target.replace({'기타산악':1}, inplace= True)
target.replace({'낙석·낙빙':1}, inplace= True)
target.replace({'산악기타':1}, inplace= True)
target.replace({'실족추락':0}, inplace= True)
target.replace({'암벽등반':1}, inplace= True)
target.replace({'야생식물 섭취 중독':1}, inplace= True)
target.replace({'일반조난':0}, inplace= True)
target.replace({'저체온증':0}, inplace= True)
target.replace({'탈진·탈수':0}, inplace= True)
target.replace({'자살기도(산악)':1}, inplace= True)

target

       사고원인코드명_사고종별
0                 0
1                 0
2                 1
3                 0
4                 0
...             ...
14481             0
14482             1
14483             1
14484             1
14485             0

[14486 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size = 0.25, stratify = target)
X_train.shape

(10864, 9)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [ ]:
knn.predict(X_test)
knn.score(X_test, y_test)

0.5386526780784097

In [ ]:
import tensorflow as tf
X_trainND = X_train.values
y_trainND = y_train.values
X_testND, y_testND = X_test.values, y_test.values
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier 
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import minmax_scale

X_scaled_train, y_scaled_train = minmax_scale(X_train), minmax_scale(y_train)
X_scaled_test, y_scaled_test = minmax_scale(X_test), minmax_scale(y_test)

In [ ]:
def create_model():
    model = Sequential()
    model.add(Dense(512, activation=tf.nn.relu))
    model.add(Dropout(0,6))
    model.add(Dense(256, activation=tf.nn.relu))
    model.add(Dropout(0,4))
    model.add(Dense(128, activation=tf.nn.relu))
    model.add(Dropout(0,2))
    model.add(Dense(2,activation = tf.nn.softmax))
    model.compile(loss = "sparse_categorical_crossentropy", optimizer="adam",metrics=['accuracy'])
    return model

In [ ]:
model1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.BatchNormalization(axis=1),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.6),
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2, activation=tf.nn.softmax)
])

In [ ]:
model1.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy']
              )

In [ ]:
model2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.BatchNormalization(axis=1),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.6),
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2, activation=tf.nn.softmax)
])
model2.compile(optimizer='adam',
             loss = 'sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [ ]:
model2.fit(X_trainND, y_trainND, epochs=5, shuffle = True)

Epoch 1/5
340/340 [==============================] - 5s 8ms/step - loss: 0.6955 - accuracy: 0.5191
Epoch 2/5
340/340 [==============================] - 3s 8ms/step - loss: 0.6907 - accuracy: 0.5265
Epoch 3/5
340/340 [==============================] - 4s 11ms/step - loss: 0.6906 - accuracy: 0.5289
Epoch 4/5
340/340 [==============================] - 3s 9ms/step - loss: 0.6889 - accuracy: 0.5378
Epoch 5/5
340/340 [==============================] - 2s 7ms/step - loss: 0.6883 - accuracy: 0.5332

In [ ]:
model2.evaluate(X_testND, y_testND)

114/114 [==============================] - 0s 3ms/step - loss: 0.6899 - accuracy: 0.5312

[0.68985915184021, 0.5311982035636902]

In [ ]:
print(X_testND)

[[23.2  0.   3.  ... 25.1  0.   0. ]
 [22.6  0.   1.2 ... 31.   0.   0. ]
 [16.8  0.   2.6 ... 13.   0.   0. ]
 ...
 [18.8  0.   1.6 ... 25.4  0.   0. ]
 [21.7  0.   3.6 ... 27.1  0.   0. ]
 [13.1  0.   0.8 ... 14.6  0.   0. ]]

In [ ]:
X_data = df.values

In [ ]:
y_pred = model2.predict(X_trainND)
y_prob = tf.nn.softmax(y_pred)

predict_probability = pd.DataFrame(y_prob, columns=['날씨 관련 사고', '날씨 관련 아닌 사고'])
predict_probability

340/340 [==============================] - 1s 2ms/step

       날씨 관련 사고  날씨 관련 아닌 사고
0      0.509766     0.490234
1      0.518566     0.481434
2      0.518564     0.481436
3      0.520957     0.479043
4      0.513542     0.486458
...         ...          ...
10859  0.508423     0.491577
10860  0.505445     0.494555
10861  0.509861     0.490139
10862  0.505543     0.494457
10863  0.522203     0.477797

[10864 rows x 2 columns]