In [1]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
data_route = '/content/gdrive/MyDrive/final_data.csv'

In [4]:
accident = pd.read_csv(data_route, encoding='UTF-8')
accident

,report_time,report_time_simple,발생장소,사고원인,지점코드,지점,지점명,기온(°C),강수량(mm),풍속(m/s),습도(%),이슬점온도(°C),현지기압(hPa),적설(cm),지면온도(°C)
0,2010-01-01 5:40,2010-01-01 5:00,전라남도 진도군 진도읍 남동리,일반조난,진도,175,진도(첨찰산),-5.6,0.0,5.9,92.0,-6.6,962.6,1.6,0.2
1,2010-01-01 5:40,2010-01-01 5:00,전라남도 진도군 진도읍 남동리,일반조난,진도,175,진도(첨찰산),-5.6,0.0,5.9,92.0,-6.6,962.6,1.6,0.2
2,2010-01-01 7:14,2010-01-01 7:00,경상북도 문경시 문경읍 상초리,일반조난,문경,273,문경,-9.9,0.0,4.3,30.0,-24.2,1000.5,0.0,-10.3
3,2010-01-01 7:31,2010-01-01 7:00,충청북도 청주시 흥덕구 산남동,개인질환,청주,131,청주,-11.4,0.0,0.6,69.0,-15.9,1016.4,0.0,-8.7
4,2010-01-01 7:47,2010-01-01 7:00,강원도 태백시 혈동 혈동,산악기타,태백,216,태백,-12.2,0.0,2.2,29.0,-26.6,930.0,0.0,-12.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86123,2021-12-31 5:14,2021-12-31 5:00,대구광역시 남구 봉덕동 봉덕동,일반조난,대구,143,대구,-4.4,0.0,5.2,41.0,-15.7,1020.7,0.0,-3.7
86124,2021-12-31 10:22,2021-12-31 10:00,광주광역시 서구 화정동 화정동,기타산악,광주,156,광주,-0.9,0.0,1.7,61.0,-7.4,1023.8,0.8,0.4
86125,2021-12-31 14:32,2021-12-31 14:00,서울특별시 은평구 진관동 진관동,실족추락,서울,108,서울,-4.3,0.0,3.5,29.0,-19.7,1020.5,0.0,4.4
86126,2021-12-31 14:58,2021-12-31 14:00,서울특별시 은평구 진관동 진관동,실족추락,서울,108,서울,-4.3,0.0,3.5,29.0,-19.7,1020.5,0.0,4.4
86127,2021-12-31 18:16,2021-12-31 18:00,대구광역시 동구 숙천동 숙천동,일반조난,대구,143,대구,-0.3,0.0,5.2,28.0,-16.6,1021.6,0.0,-1.4

In [5]:
target = pd.DataFrame(accident['사고원인'])

In [6]:
target

       사고원인
0      일반조난
1      일반조난
2      일반조난
3      개인질환
4      산악기타
...     ...
86123  일반조난
86124  기타산악
86125  실족추락
86126  실족추락
86127  일반조난

[86128 rows x 1 columns]

In [8]:
column_list = accident.columns.to_list()
column_list = column_list[7:23]

In [9]:
accident[column_list]

       기온(°C)  강수량(mm)  풍속(m/s)  습도(%)  이슬점온도(°C)  현지기압(hPa)  적설(cm)  지면온도(°C)
0        -5.6      0.0      5.9   92.0       -6.6      962.6     1.6       0.2
1        -5.6      0.0      5.9   92.0       -6.6      962.6     1.6       0.2
2        -9.9      0.0      4.3   30.0      -24.2     1000.5     0.0     -10.3
3       -11.4      0.0      0.6   69.0      -15.9     1016.4     0.0      -8.7
4       -12.2      0.0      2.2   29.0      -26.6      930.0     0.0     -12.6
...       ...      ...      ...    ...        ...        ...     ...       ...
86123    -4.4      0.0      5.2   41.0      -15.7     1020.7     0.0      -3.7
86124    -0.9      0.0      1.7   61.0       -7.4     1023.8     0.8       0.4
86125    -4.3      0.0      3.5   29.0      -19.7     1020.5     0.0       4.4
86126    -4.3      0.0      3.5   29.0      -19.7     1020.5     0.0       4.4
86127    -0.3      0.0      5.2   28.0      -16.6     1021.6     0.0      -1.4

[86128 rows x 8 columns]

In [10]:
num_of_falls = len(accident[accident['사고원인'] == '야생식물 섭취 중독'])

# 결과를 출력합니다.
print(num_of_falls)

26

In [11]:
df = accident[['기온(°C)', '강수량(mm)','풍속(m/s)','습도(%)', '이슬점온도(°C)', '적설(cm)','지면온도(°C)']]
df.loc[df['강수량(mm)']==0.0, '강수여부'] = 0
df.loc[df['강수량(mm)']>0.0, '강수여부'] = 1
df.loc[df['적설(cm)']==0.0, '적설여부'] = 0
df.loc[df['적설(cm)']>0.0, '적설여부'] = 1

df

<ipython-input-11-9a8b637d8f82>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['강수량(mm)']==0.0, '강수여부'] = 0
<ipython-input-11-9a8b637d8f82>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['적설(cm)']==0.0, '적설여부'] = 0

,기온(°C),강수량(mm),풍속(m/s),습도(%),이슬점온도(°C),적설(cm),지면온도(°C),강수여부,적설여부
0,-5.6,0.0,5.9,92.0,-6.6,1.6,0.2,0.0,1.0
1,-5.6,0.0,5.9,92.0,-6.6,1.6,0.2,0.0,1.0
2,-9.9,0.0,4.3,30.0,-24.2,0.0,-10.3,0.0,0.0
3,-11.4,0.0,0.6,69.0,-15.9,0.0,-8.7,0.0,0.0
4,-12.2,0.0,2.2,29.0,-26.6,0.0,-12.6,0.0,0.0
...,...,...,...,...,...,...,...,...,...
86123,-4.4,0.0,5.2,41.0,-15.7,0.0,-3.7,0.0,0.0
86124,-0.9,0.0,1.7,61.0,-7.4,0.8,0.4,0.0,1.0
86125,-4.3,0.0,3.5,29.0,-19.7,0.0,4.4,0.0,0.0
86126,-4.3,0.0,3.5,29.0,-19.7,0.0,4.4,0.0,0.0
86127,-0.3,0.0,5.2,28.0,-16.6,0.0,-1.4,0.0,0.0

In [12]:
import scipy.stats as stats

for item in df:
  for item2 in df:
    if stats.pearsonr(df[item],df[item2]).statistic > 0.5:
      print(item,"+",item2,"=",stats.pearsonr(df[item],df[item2]))

기온(°C) + 기온(°C) = PearsonRResult(statistic=1.0, pvalue=0.0)
기온(°C) + 이슬점온도(°C) = PearsonRResult(statistic=0.8424882098500233, pvalue=0.0)
기온(°C) + 지면온도(°C) = PearsonRResult(statistic=0.8934705532117841, pvalue=0.0)
강수량(mm) + 강수량(mm) = PearsonRResult(statistic=0.9999999999999771, pvalue=0.0)
풍속(m/s) + 풍속(m/s) = PearsonRResult(statistic=0.9999999999999978, pvalue=0.0)
습도(%) + 습도(%) = PearsonRResult(statistic=0.9999999999999961, pvalue=0.0)
습도(%) + 이슬점온도(°C) = PearsonRResult(statistic=0.6189481538482868, pvalue=0.0)
이슬점온도(°C) + 기온(°C) = PearsonRResult(statistic=0.8424882098500233, pvalue=0.0)
이슬점온도(°C) + 습도(%) = PearsonRResult(statistic=0.6189481538482868, pvalue=0.0)
이슬점온도(°C) + 이슬점온도(°C) = PearsonRResult(statistic=1.0, pvalue=0.0)
이슬점온도(°C) + 지면온도(°C) = PearsonRResult(statistic=0.6705503073559016, pvalue=0.0)
적설(cm) + 적설(cm) = PearsonRResult(statistic=0.9999999999999967, pvalue=0.0)
적설(cm) + 적설여부 = PearsonRResult(statistic=0.6628400542294837, pvalue=0.0)
지면온도(°C) + 기온(°C) = PearsonRResult(statistic=0.8934705532117841, pvalue=0.0)
지면온도(°C) + 이슬점온도(°C) = PearsonRResult(statistic=0.6705503073559016, pvalue=0.0)
지면온도(°C) + 지면온도(°C) = PearsonRResult(statistic=0.9999999999999987, pvalue=0.0)
강수여부 + 강수여부 = PearsonRResult(statistic=1.0, pvalue=0.0)
적설여부 + 적설(cm) = PearsonRResult(statistic=0.6628400542294837, pvalue=0.0)
적설여부 + 적설여부 = PearsonRResult(statistic=1.0, pvalue=0.0)

In [17]:
target.replace({'개인(급.만성)질환':1}, inplace= True)
target.replace({'개인질환':1}, inplace= True)
target.replace({'고온환경질환':1}, inplace= True)
target.replace({'기타산악':1}, inplace= True)
target.replace({'낙석·낙빙':1}, inplace= True)
target.replace({'산악기타':1}, inplace= True)
target.replace({'실족추락':0}, inplace= True)
target.replace({'암벽등반':1}, inplace= True)
target.replace({'야생식물 섭취 중독':1}, inplace= True)
target.replace({'일반조난':0}, inplace= True)
target.replace({'저체온증':0}, inplace= True)
target.replace({'탈진·탈수':0}, inplace= True)
target.replace({'자살기도':1}, inplace= True)

target

       사고원인
0         0
1         0
2         0
3         1
4         1
...     ...
86123     0
86124     1
86125     0
86126     0
86127     0

[86128 rows x 1 columns]

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size = 0.25, stratify = target)
X_train.shape

(64596, 9)

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [20]:
knn.predict(X_test)
knn.score(X_test, y_test)

0.5813208248188743

In [21]:
import tensorflow as tf
X_trainND = X_train.values
y_trainND = y_train.values
X_testND, y_testND = X_test.values, y_test.values
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier 
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import minmax_scale

X_scaled_train, y_scaled_train = minmax_scale(X_train), minmax_scale(y_train)
X_scaled_test, y_scaled_test = minmax_scale(X_test), minmax_scale(y_test)

In [22]:
def create_model():
    model = Sequential()
    model.add(Dense(512, activation=tf.nn.relu))
    model.add(Dropout(0,6))
    model.add(Dense(256, activation=tf.nn.relu))
    model.add(Dropout(0,4))
    model.add(Dense(128, activation=tf.nn.relu))
    model.add(Dropout(0,2))
    model.add(Dense(2,activation = tf.nn.softmax))
    model.compile(loss = "sparse_categorical_crossentropy", optimizer="adam",metrics=['accuracy'])
    return model

In [23]:
model1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.BatchNormalization(axis=1),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.6),
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2, activation=tf.nn.softmax)
])

In [24]:
model1.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy']
              )

In [25]:
model2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.BatchNormalization(axis=1),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.6),
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2, activation=tf.nn.softmax)
])
model2.compile(optimizer='adam',
             loss = 'sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [26]:
model2.fit(X_trainND, y_trainND, epochs=5, shuffle = True)

Epoch 1/5
2019/2019 [==============================] - 18s 8ms/step - loss: 0.6899 - accuracy: 0.5448
Epoch 2/5
2019/2019 [==============================] - 16s 8ms/step - loss: 0.6868 - accuracy: 0.5498
Epoch 3/5
2019/2019 [==============================] - 15s 8ms/step - loss: 0.6865 - accuracy: 0.5514
Epoch 4/5
2019/2019 [==============================] - 15s 8ms/step - loss: 0.6864 - accuracy: 0.5533
Epoch 5/5
2019/2019 [==============================] - 15s 8ms/step - loss: 0.6862 - accuracy: 0.5531

In [27]:
model2.evaluate(X_testND, y_testND)

673/673 [==============================] - 2s 2ms/step - loss: 0.6850 - accuracy: 0.5563

[0.6849558353424072, 0.5563347339630127]

In [28]:
print(X_testND)

[[23.   0.   2.5 ... 31.4  0.   0. ]
 [14.1  0.   1.8 ... 14.6  0.   0. ]
 [21.8  0.   2.  ... 17.6  0.   0. ]
 ...
 [ 9.   0.   1.5 ... 10.   0.   0. ]
 [ 4.5  0.   0.8 ...  1.   0.   0. ]
 [21.5  0.   2.4 ... 28.4  0.   0. ]]

In [29]:
X_data = df.values

In [30]:
y_pred = model2.predict(X_trainND)
y_prob = tf.nn.softmax(y_pred)

predict_probability = pd.DataFrame(y_prob, columns=['날씨 관련 사고', '날씨 관련 아닌 사고'])
predict_probability

2019/2019 [==============================] - 5s 3ms/step

       날씨 관련 사고  날씨 관련 아닌 사고
0      0.482353     0.517647
1      0.474195     0.525805
2      0.478668     0.521332
3      0.479263     0.520737
4      0.480393     0.519607
...         ...          ...
64591  0.447055     0.552945
64592  0.465187     0.534813
64593  0.504943     0.495056
64594  0.485847     0.514153
64595  0.496230     0.503770

[64596 rows x 2 columns]